---
# Run this play as root user
- hosts: localhost
  gather_facts: no
  roles:
    - role: kubectl
      tags: kubectl     
    - role: tls
      tags: tls

# second play
- name: Distribute TLS related files
  hosts: others
  gather_facts: yes
  tasks:
    - name: create a directory if it doesn't exist
      file:
        name: /etc/kubernetes/pki/etcd
        state: directory
      tags: disTLS

    - name: Distribute /etc/kubernetes kubeconfig files
      copy:
        src: "{{ item }}"
        dest: /etc/kubernetes
        mode: preserve
      with_fileglob:
        - /etc/kubernetes/*.kubeconfig
      tags: disTLS

    - name: Distribute /etc/kubernetes/pki TLS key and certificate files
      copy:
        src: "{{ item }}"
        dest: /etc/kubernetes/pki
        mode: preserve
      with_fileglob:
        - /etc/kubernetes/pki/*.crt
        - /etc/kubernetes/pki/*.pub
        - /etc/kubernetes/pki/*.csr
        - /etc/kubernetes/pki/*.key
      tags: disTLS

    - name: Distribute /etc/kubernetes/pki/etcd TLS key and certificate files
      copy:
        src: "{{ item }}"
        dest: /etc/kubernetes/pki/etcd
        mode: preserve
      with_fileglob:
        - /etc/kubernetes/pki/etcd/*.crt
        - /etc/kubernetes/pki/etcd/*.csr
        - /etc/kubernetes/pki/etcd/*.key
      tags: disTLS

# third play Allnode
- name: install docker
  hosts: Allnode
  gather_facts: yes
  roles:
    - role: docker
      tags: docker

# Fourth play
- name: install etcd3
  hosts: etcd
  gather_facts: yes
  roles:
    - role: etcd
      tags: etcd

# Fifth play
- name: master API server high availability
  hosts: master
  gather_facts: yes
  roles:
    - { role: HA, tags: HA, when: "groups['master'] | length  != 1" }

 
# 6 play ansible-playbook deploy.yml -e "redo=true" --tags "master"
- name: deploy master components( kube-apiserver,kube-controller-manager,kube-scheduler)
  hosts: master
  gather_facts: yes
  roles:
    - role: master
      tags: master

# 7 Generate TLS bootstrapping kubeconfig,secret as well as cluster-role binding
- name: kublet TLS bootstrapping configuration
  hosts: localhost
  gather_facts: no
  roles:
    - role: bootstrap
      tags: bootstrap
