# create a directory if it doesn't exist
- file:
    name: /etc/kubernetes/pki/etcd 
    state: directory

- name: Generate Certificate Authority and certificate and key files
  include_tasks:
    file: tls.yml

- name: Generate kubeconfig files
  include_tasks:
    file: kubeconfig.yml
