- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Setting System Timezone
  timezone:
    name: "{{ TimeZone  }}"
  when: TimeZone is defined


- name: Distribute systemd-timesyncd configuration file
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode:  '0644'
