# ansible configuration
ansible_connection: ssh
ansible_user: root
ansible_port: 22
ansible_ssh_private_key_file: '~/.ssh/id_rsa'
ansible_python_interpreter: /usr/bin/python3.6

# system time zone configuration
TimeZone: 'Asia/Shanghai'
kernel: true
ntp_server1: 'cn.pool.ntp.org'
ntp_server2: 'tw.pool.ntp.org'

swap: false

# openssl.cnf template
# if etcd or master needs extension, fill resevered IPs
# certSANs:
#   apiServer:
#     - 10.200.209.156
#     - 10.200.209.157
#   etcd:
#     - 10.200.209.158

SvcCIDR: 172.16.0.0/16
KubernetesClusterSVCIP: 172.16.0.1 # Used for Certificate SAN
ClusterDns: 172.16.0.10  # Userd for CoreDNS cluster IP
PodCIDR: 192.168.0.0/16
ServiceNodePortRange: 30000-32767
ClusterDomain: cluster.local

CLUSTER_NAME: 'kubernetes'
KUBE_VERSION: 'v1.14.1'
ETCD_version: 'v3.2.24'

# ApiServer high availability
VIP: '10.220.209.200'
KUBE_APISERVER: https://{% if groups['master'] | length !=1 %}{{ VIP }}:8443{% else %}{{ hostvars[groups['master'][0]].inventory_hostname }}:6443{% endif %}
VIP_NETMASK: 24
INTERFACE_NAME: ens192
