- name: remove ntp
  package: name=ntp state=absent
  ignore_errors: True

- name: Install chrony
  package: name=chrony state=latest

- name: Send chrony configuration file
  template: src=chrony.conf.j2 dest=/etc/chrony.conf
