# ansible configuration
ansible_connection: ssh
ansible_user: root
ansible_port: 22
ansible_ssh_private_key_file: '~/.ssh/union_rsa'
ansible_python_interpreter: /usr/bin/python

# turn on below configuration to install kubernetes dashboard
dashboard:
  enable: false
APP_DOMAIN_NAME: onpremises.bizconf.cn
OPS_DOMAIN_NAME: opscustomer.bizconf.cn
