- name: Delete default Ubuntu Installation (5 items)
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: true
    state: absent
  loop:
    - ufw
    - lxd
    - lxd-client
    - lxcfs
    - lxc-common
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  ignore_errors: true

- name: Update apt-get repo and cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 72000
    force_apt_get: true
  ignore_errors: true
  when:
  - 'ansible_distribution in ["Ubuntu","Debian"]'

# https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
- name: Upgrade all apt packages
  become: yes
  apt:
    upgrade: dist
    force_apt_get: yes

##############################
# Install softwares
##############################
- name: Install common used softwares
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    force_apt_get: yes
  loop:
    - bash-completion # bash command completion tool
    - conntrack       # used in network connection cleanup
    - jq              # for container image query
    - sysstat
    - vim
    # - ntp
    - lsof
  when:
  - 'ansible_distribution in ["Ubuntu","Debian"]'

- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  stat: path=/var/run/reboot-required 

- name: Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
