debug:
  enabled: true
  verbose: flow kvstore envoy datapath policy

healthChecking: true

endpointHealthChecking:
  # -- Enable connectivity health checking between virtual endpoints.
  enabled: true

cluster:
  name: test
  id: 1

ipv4:
  enabled: false
ipv6:
  enabled: true
enableIPv4BIGTCP: false
enableIPv6BIGTCP: true

enableIPv4Masquerade: false
enableIPv6Masquerade: true
ipMasqAgent:
  enabled: false


kubeProxyReplacement: "true"
# cluster name is test
k8sServiceHost: test-control-plane
k8sServicePort: 6443

routingMode: "native"
ipv6NativeRoutingCIDR: "fd00:20:1::/48"
autoDirectNodeRoutes: true
enableCiliumEndpointSlice: false
endpointRoutes:
  enabled: true

bpf:
  masquerade: true
  datapathMode: netkit

ipam:
  #mode: "cluster-pool"
  mode: "kubernetes"

  operator:
    clusterPoolIPv6PodCIDRList: ["fd00:20:1::/104"]
    clusterPoolIPv6MaskSize: 120

nodePort:
  enabled: true

bgpControlPlane:
  enabled: true

operator:
  replicas: 1

  prometheus:
    enabled: true

