kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.0"
  - role: worker
    image: "kindest/node:v1.30.0"
  - role: worker
    image: "kindest/node:v1.30.0"
networking:
  ipFamily: ipv4
  #apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.0.0/16
  disableDefaultCNI: true
  kubeProxyMode: none
