apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: test
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=controlplane"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
networking:
  ipFamily: ipv6
  apiServerPort: 6443
  podSubnet: fd00:20:1::/48
  serviceSubnet: fd00:10:200::/108
  disableDefaultCNI: true
  kubeProxyMode: none
