- name: Create etcd-related folders
  file: 
    name: "{{ item }}"
    state: directory
  loop:
    - /etc/kubernetes/pki/etcd
    - "{{ etcd.dataDir }}"
    - /etc/etcd


- name: Distribute etcd executable files
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: preserve
  loop:
    - /home/plcm/kubernetes/etcd
    - /home/plcm/kubernetes/etcdctl

- name: Distribute etcd configuration file and system service file
  template: src=templates/{{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  loop:
    - { src: 'etcd.config.yml.j2', dest: '/etc/etcd' }
    - { src: 'etcd.service.j2', dest: '/etc/systemd/system' }


- name: Renderer etcdctl scripts
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
  - { src: 'etcdctl.sh.j2', dest: '/usr/local/bin/'}
  connection: local
  run_once: true

- name: start and enable etcd
  systemd:
    name: etcd 
    state: restarted 
    enabled: yes 
    daemon_reload: yes
  when: not ( redo | default(false) )
