apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: yb-tserver
    yugabyte.com/ybcluster-name: ybcluster
  name: datadir0-yb-tserver-0
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 375Gi
  storageClassName: localpath
  volumeMode: Filesystem
  volumeName: pv-datadir0-yb-tserver-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    name: pv-datadir0-yb-tserver-0
  name: pv-datadir0-yb-tserver-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 375Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir0-yb-tserver-0
    namespace: prod
  local:
    path: /mnt/disks/ssd0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-cluster-gke-yuga-pool-1-845fc479-nnc2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localpath
  volumeMode: Filesystem
