apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: bgpv2-service
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=controlplane"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
networking:
  ipFamily: ipv4
  #apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.0.0/16
  disableDefaultCNI: true
  kubeProxyMode: none
