---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-blue"
  labels:
    bgp: blue
spec:
  blocks:
    - cidr: "10.100.10.0/24"
  serviceSelector:
    matchExpressions:
      - {key: bgp, operator: In, values: [blue]}
