- import_tasks: kubelet.yml
  tags:
    - kubelet

- import_tasks: kube-proxy.yml
  tags:
    - kube-proxy

- name: 轮询等待kubelet启动
  shell: "systemctl status kubelet.service | grep Active"
  register: kubelet_status
  until: '"running" in kubelet_status.stdout'
  retries: 8
  delay: 2

