# Generate configuration files for deploying kubernetes
- hosts: local_host
  gather_facts: no
  vars_prompt:
    - name: private_ip_str
      prompt: "Please input host private ip(s), separated by commas"
      private: no
  roles:
    - role: configs
      tags: configs


