---
 - hosts: all
   tasks:
   - name: hostname lists
     debug:
       var=ansible_hostname

   - name: date and time
     vars:
       msgs: |
         Date: {{ ansible_date_time.date }}
         Timezone: {{ ansible_date_time.tz }}
     debug:
       msg: "{{ msgs.split('\n') }}"

   - name: set static IP fact
     set_fact:
       net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

   - name: show IP CIDR
     debug:
       msg: "{{ net_mask | ipaddr('net') }}"

   - name: show host CIDR host/prefix
     debug:
       msg: "{{ '192.168.1.1/24' | ipmath(6) }}"

   - name: network info
     vars:
       msg: |
         All Interface List: {{ ansible_interfaces }}
         All IP: {{ ansible_all_ipv4_addresses }}
         IP: {{ ansible_default_ipv4.address }}
         Interface: {{ ansible_default_ipv4.interface }}
         Network: {{ ansible_default_ipv4.network }}
         Gateway: {{ ansible_default_ipv4.gateway }}
     debug:
       msg: "{{ msg.split('\n') }}"

   - name: OS and Kernel info
     vars:
       msg: |
         Distribution: {{ ansible_distribution }}
         Release: {{ ansible_distribution_release }}
         Distribution Version: {{ ansible_distribution_version }}
         Kernel: {{ ansible_kernel }}
         Architecture: {{ ansible_architecture }} 
     debug:
       msg: "{{ msg.split('\n') }}"


   - name: HW Info
     vars:
       msg: |
         CPU: {{ ansible_processor }}
         CPU Core: {{ ansible_processor_cores }}
         RAM: {{ ansible_memtotal_mb }}
         SWAP: {{ ansible_memory_mb.swap.total }}
     debug:
       msg: "{{ msg.split('\n') }}"
