{{- if .Values.addHeaders }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx-ingress.fullname" . }}-custom-add-headers
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
    component: {{ .Values.name }}
data: {{- toYaml .Values.addHeaders | nindent 2 }}
{{- end }}
