{{- if gt (.Values.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nginx-ingress.fullname" . }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
    component: {{ .Values.name }}
spec:
  selector:
    matchLabels: {{- include "nginx-ingress.labels" . | nindent 6 }}
      component: {{ .Values.name }}
  minAvailable: {{ .Values.minAvailable }}
{{- end }}
