{{- if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-ingress.defaultBackend.fullname" . }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
    component: {{ .Values.defaultBackend.name }}
  {{- if .Values.defaultBackend.service.annotations }}
  annotations: {{- include "nginx-ingress.tplValue" (dict "value" .Values.defaultBackend.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.defaultBackend.service.type }}
  ports:
    - name: http
      port: {{ .Values.defaultBackend.service.port }}
      protocol: TCP
      targetPort: http
  selector: {{- include "nginx-ingress.matchLabels" . | nindent 4 }}
    component: {{ .Values.defaultBackend.name }}
{{- end }}
