{{- if and .Values.defaultBackend.enabled (gt (.Values.defaultBackend.replicaCount | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nginx-ingress.defaultBackend.fullname" . }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
    component: {{ .Values.defaultBackend.name }}
spec:
  selector:
    matchLabels: {{- include "nginx-ingress.matchLabels" . | nindent 4 }}
      component: {{ .Values.defaultBackend.name }}
  minAvailable: {{ .Values.defaultBackend.minAvailable }}
{{- end }}
