{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nginx-ingress.serviceAccountName" . }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- end -}}
