- name: install haproxy
  apt:
    name: haproxy
    update_cache: yes
    state: latest

- name: distribute haproxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
