---
# Run this playbook as root user
- hosts: Allnode
  gather_facts: yes
  roles:
    - osharden
  tags:
    - osharden

- name: Install docker on all nodes
  hosts: Allnode
  gather_facts: yes
  roles:
    - role: docker
      tags: docker
