# Run the script as root user
- hosts: Allnode
  gather_facts: yes
  roles:
    - prepare
  tags:
    - prepare

- hosts: localhost
  gather_facts: no
  vars:
  roles:
    - role: tls
      tags: tls

- name: Install etcd3 on all etcd-related nodes
  hosts: etcd
  gather_facts: yes
  roles:
    - role: etcd
      tags: etcd
      
- name: Distribute TLS to master/worker nodes
  hosts: Allnode
  gather_facts: yes
  roles:
    - role: disTLS
      tags: disTLS
      
#- name: master API server high availability
 # hosts: master
 # gather_facts: yes
 # roles:
 #   - { role: HA, tags: HA, when: "groups['master'] | length  != 1" }

- name: deploy master components( kube-apiserver,kube-controller-manager,kube-scheduler)
  hosts: master
  gather_facts: yes
  roles:
    - role: master
      tags: master
